version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
