version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Set up Kotlin
          command: |
            curl -sSL https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin

      - run:
          name: Make gradlew executable
          command: chmod +x gradlew
      - run:
          name: Run Tests
          command: ./gradlew test
